### ISSUE TITLE
What is needed in the zocalo credentials.cfg file?

### ISSUE THREAD

**Issue by dsclassen** [DiamondLightSource/python-zocalo#17]
What needs to be in this file?

https://github.com/DiamondLightSource/python-zocalo/blob/768913f3a7fe71673eb8d30804fbaf181d0c36e6/zocalo/service/__init__.py#L63

**Comment by Anthchirp** [comment]
In Zocalo 0.8 this Diamond-specific file will be replaced with a [site configuration file](https://zocalo.readthedocs.io/en/latest/siteconfig.html), and the stomp credential block will be [described in the workflows package](https://github.com/DiamondLightSource/python-workflows/tree/main/src/workflows/util/zocalo)
