### ISSUE TITLE
Clarification needed for JMX configuration

### ISSUE THREAD

**Issue by dsclassen** [DiamondLightSource/python-zocalo#180]
It is not clear to me how to configure JMX in the [site-configuration.yml](https://github.com/DiamondLightSource/python-zocalo/blob/d8f44e0ebc902109ce99eb2e5ed07c976b876234/contrib/site-configuration.yml) file.

We have Graylog and ActiveMQ configured, and are trying to configure JMX as per these [instructions](https://zocalo.readthedocs.io/en/latest/getting_started.html#jmx).

```
# grep Jolokia  activemq.log
2022-05-17 12:18:32,959 | INFO  | ActiveMQ Jolokia REST API available at http://0.0.0.0:8161/api/jolokia/ | org.apache.activemq.web.WebConsoleStarter | main
```

So I conclude that these three lines of configuration need to be added somewhere:

```
port: 8161
host: localhost
base_url: api/jolokia
```

but as a "plugin"? how should the encapsulating YAML be constructed? or does this go in a separate file?

**Comment by rjgildea** [comment]
You can put the jmx credentials in a separate file, e.g.:
```
$ cat /path/to/activemq-jmx-credentials.yaml
plugin: jmx
host: localhost
port: 8161
username: user
password: letmein
base_url: api/jolokia
```
and then reference this in your zocalo config yaml:
```
$ cat /path/to/zocalo/configuration.yaml
...
activemq-jmx: /dls_sw/apps/zocalo/secrets/activemq-jmx-credentials.yaml
...
environments:
  default: live

  live:
    ...
    plugins:
    - activemq-jmx
    ...
```
Alternatively you could define it in the configuration yaml directly, however this may not be a good idea if you want to keep your configuration in version control:
$ cat /path/to/zocalo/configuration.yaml
...
activemq-jmx:
    plugin: jmx
    host: localhost
    port: 8161
    username: user
    password: letmein
    base_url: api/jolokia
...
environments:
  default: live

  live:
    ...
    plugins:
    - activemq-jmx
    ...
```

However, I should mention that we have recently invested a significant amount of effort in moving Zocalo to RabbitMQ, and would strongly recommend this in preference to ActiveMQ. We haven't quite decided to what extent we will maintain support for the `StompTransport` class going forward, but it is very likely that we will take further advantage of RabbitMQ-specific features in developing future functionality.

This does highlight that we need to revisit the documentation in light of the RabbitMQ developments.
