### ISSUE TITLE
recipe_ID no longer logged in wrappers

### ISSUE THREAD

**Issue by rjgildea** [DiamondLightSource/python-zocalo#192]
Since the logging plugin was added in #176, logged messages from Zocalo wrappers are no longer annotated with the `recipe_ID`, as this code is specific to the (now deprecated) graylog plugin:

https://github.com/DiamondLightSource/python-zocalo/blob/a638ced8ab5c8103f2668a8d76a87cb06a28def9/src/zocalo/cli/wrap.py#L130-L137

As the logging plugin now uses the `logging.config.dictConfig` mechanism, it isn't obvious to me how to easily replicate this functionality  with the logging plugin.

**Comment by Anthchirp** [comment]
There are nicer and less nice options. One could be to add a `RecipeIDFilter` to the configuration (and `zocalo.configuration.plugin_logging`) which does nothing by default. Then at this point in the code you could introspect the logging tree to find all RecipeIDFilter instances and tell them the recipe ID to attach to log messages. Or use the power of a shared singleton to achieve the same in a not so nice way. Could even turn this into a context manager, which would then get close to how services (specifically, the dispatcher) do the same thing.

Dunno, just a few ideas while I'm waiting for other things to complete.

**Comment by rjgildea** [comment]
Thanks for the pointers - I had wondered whether something along the lines of what the services do via `extend_log` might be a solution, although the context manager might not be necessary here as (I think) a wrapper instance would only ever see a single recipe.

**Comment by Anthchirp** [comment]
Yes, this is true.

**Comment by rjgildea** [comment]
It turns out it's actually far easier than initially thought to just use a [`LoggingAdapter`](https://docs.python.org/3/library/logging.html#loggeradapter-objects) to add the `recipe_ID` :)
