### ISSUE TITLE
RabbitMQ: Schlockmeister - Channel subscriptions

### ISSUE THREAD

**Issue by Anthchirp** [DiamondLightSource/python-zocalo#69]
Schlockmeister currently uses the ActiveMQ `ActiveMQ.Advisory.Consumer.Queue.` facility to be notified when new queues appear (or more specifically: when new subscribers appear on any queue), and it uses listening on a special queue as a marker for quorum sensing (detecting other Schlockmeister instances nearby).

We will have to find an equivalent way how we can determine what queues we should be listening to on RabbitMQ.

**Comment by d-j-hatton** [comment]
pika does not provide a method for accessing a list of queues on the RabbitMQ server. Such a list can be accessed through rabbitmqctl but it may be better to reorganise how Schlockmeister operates. Further discussion of related issues in #70

**Comment by Anthchirp** [comment]
As things stand Schlockmeister can be retired with the move to RabbitMQ
