### ISSUE TITLE
RabbitMQ: Delayed message exchange

### ISSUE THREAD

**Issue by Anthchirp** [DiamondLightSource/python-zocalo#71]
Evaluate RabbitMQ server side https://github.com/rabbitmq/rabbitmq-delayed-message-exchange vs. a service that controls message delay

**Comment by Anthchirp** [comment]
Plugin is now deployed on all three servers

**Comment by rjgildea** [comment]
Closed by https://github.com/DiamondLightSource/python-zocalo/pull/169
